[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.9" # Solana version to use

[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[workspace]
members = [
    "programs/merkle-distributor",
]

[provider]
cluster = "devnet"
wallet = "/home/anusriesto/.config/solana/id.json"


[programs.devnet]
merkle_distributor = "G15pAFExGrHqAeSLRPPrXzCXFqJpajhSaTic7pWzJEU7"

[programs.localnet]
merkle_distributor = "G15pAFExGrHqAeSLRPPrXzCXFqJpajhSaTic7pWzJEU7"

[programs.mainnet]
merkle_distributor = "G15pAFExGrHqAeSLRPPrXzCXFqJpajhSaTic7pWzJEU7"

[scripts]
test = "yarn mocha"
